export const allProduct = [
  {
    id: 1,
    image: "/productImg1.webp",
    title: "Bus Mania : Station Shuffle Game Buy Unity Source Code",
    category: "Game Template",
    price: "15",
    inStock: 5,
  },
  {
    id: 2,
    image: "/productImg2.png",
    title: "Deliver It 3D Game Unity 3D Source Code",
    category: "Car Racing Game",
    price: "20",
    inStock: 3,
  },
  {
    id: 3,
    image: "/productImg3.webp",
    title: "Human vs Alien – Multiplayer Game Buy Unity Source Code",
    category: "RPG Template",
    price: "25",
    inStock: 7,
  },
  {
    id: 4,
    image: "/productImg4.webp",
    title: "Metal Black OPS Game Buy Unity Source Code",
    category: "Puzzle Game",
    price: "10",
    inStock: 2,
  },
  {
    id: 5,
    image: "/productImg5.webp",
    title: "Tactical Knight Game – Buy Unity Games",
    category: "Space Shooter",
    price: "18",
    inStock: 6,
  },
  {
    id: 6,
    image: "/productImg6.webp",
    title: "New Year Simulation Bundle 10 Best Unity Game Source Code",
    category: "Game Template",
    price: "16",
    inStock: 4,
  },
  {
    id: 7,
    image: "/productImg7.webp",
    title: "Santa's Christmas Bundle Top 10 Unity Game Source Code",
    category: "Game Template",
    price: "16",
    inStock: 8,
  },
  {
    id: 8,
    image: "/productImg8.webp",
    title: "Summer Special Deal 30 Unity Source Code Bundle",
    category: "Game Template",
    price: "26",
    inStock: 3,
  },
  {
    id: 9,
    image: "/productImg9.webp",
    title: "Ultimate Winter Deal Get 100 Plus Games",
    category: "Game Template",
    price: "16",
    inStock: 5,
  },
  {
    id: 10,
    image: "/productImg10.webp",
    title: "Unity Hyper Pack 17 Games Source Code Deal",
    category: "Game Template",
    price: "30",
    inStock: 2,
  },
  {
    id: 11,
    image: "/productImg11.webp",
    title: "Buy Unity Source Code | Empire.io ",
    category: "Game Template",
    price: "15",
    inStock: 6,
  },
  {
    id: 12,
    image: "/productImg12.webp",
    title: "Buy Unity Games | Draw Puzzle Story",
    category: "Car Racing Game",
    price: "20",
    inStock: 4,
  },
  {
    id: 13,
    image: "/productImg13.webp",
    title: "Buy Unity Games | Dead Flip Challenge",
    category: "RPG Template",
    price: "25",
    inStock: 7,
  },
  {
    id: 14,
    image: "/productImg14.webp",
    title: "Circus Dart Wheel Game – Unity Games Source Code",
    category: "Puzzle Game",
    price: "10",
    inStock: 3,
  },
  {
    id: 15,
    image: "/productImg15.webp",
    title: "Chop & Mine Idle Game – Buy Unity Source Code",
    category: "Space Shooter",
    price: "18",
    inStock: 5,
  },
  {
    id: 16,
    image: "/productImg16.webp",
    title: "Block Shooter Game – Buy Unity Source Code",
    category: "Game Template",
    price: "16",
    inStock: 2,
  },
  {
    id: 17,
    image: "/productImg17.webp",
    title: "Brain Master Puzzle Game – Buy Unity Game Source Code",
    category: "Game Template",
    price: "16",
    inStock: 6,
  },
  {
    id: 18,
    image: "/productImg18.webp",
    title: "Ball Thrower Game – Buy Unity Source Code",
    category: "Game Template",
    price: "26",
    inStock: 4,
  },
  {
    id: 19,
    image: "/productImg19.webp",
    title: "Big Head Game – Buy Unity Source Code",
    category: "Game Template",
    price: "16",
    inStock: 8,
  },
  {
    id: 20,
    image: "/productImg20.webp",
    title: "Squid Game 7 Challenge Game Buy Unity Source Code",
    category: "Game Template",
    price: "30",
    inStock: 3,
  },
];
